//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FavoriFilmler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favoriler
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public string Title { get; set; }
        public int Year { get; set; }
        public double Imdb_Rating { get; set; }
        public string Director { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
